export const sortCategoryData = ["All", "Popular", "Recommended", "More"];
export const langTranslate = [
  { label: "অসমীয়া (Assamese)", code: "as", value: 1 },
  { label: "বাংলা (Bangla)", code: "bn", value: 2 },
  { label: "बर (Boro)", code: "brx", value: 3 },
  { label: "डोगरी (Dogri)", code: "doi", value: 4 },
  { label: "English", code: "en", value: 5 },
  { label: "गोंय (Goan-Konkani)", code: "gom", value: 6 },
  { label: "ગુજરાતી (Gujarati)", code: "gu", value: 7 },
  { label: "हिंदी (Hindi)", code: "hi", value: 8 },
  { label: "ಕನ್ನಡ (Kannada)", code: "kn", value: 9 },
  { label: "کاشمیری (Kashmiri (Arabic))", code: "ks", value: 10 },
  { label: "कश्मीरी (Kashmiri (Devanagari))", code: "ks_Deva", value: 11 },
  { label: "मैथिली (Maithili)", code: "mai", value: 12 },
  { label: "മലയാളം (Malayalam)", code: "ml", value: 13 },
  { label: "ꯃꯅꯤꯄꯨꯔꯤ (Manipuri (Meitei))", code: "mni", value: 14 },
  { label: "মনিপুরী (Manipuri (Bengali))", code: "mni_Beng", value: 15 },
  { label: "मराठी (Marathi)", code: "mr", value: 16 },
  { label: "नेपाली (Nepali)", code: "ne", value: 17 },
  { label: "ଓରିଆ (Oriya)", code: "or", value: 18 },
  { label: "ਪੰਜਾਬੀ (Panjabi)", code: "pa", value: 19 },
  { label: "संस्कृतं (Sanskrit)", code: "sa", value: 20 },
  { label: "ᱥᱚᱱᱛᱟᱞᱤ ᱾ (Santali)", code: "sat", value: 21 },
  { label: "سنڌی (Sindhi (Arabic))", code: "sd", value: 22 },
  { label: "सिंधी (Sindhi (Devanagari))", code: "sd_Deva", value: 23 },
  { label: "தமிழ் (Tamil)", code: "ta", value: 24 },
  { label: "తెలుగు (Telugu)", code: "te", value: 25 },
  { label: "اردو (Urdu)", code: "ur", value: 26 },
];

export const langSpeech = [
  { label: "বাংলা (Bangla)", code: "bn", value: 1 },
  { label: "English", code: "en", value: 2 },
  { label: "ગુજરાતી (Gujarati)", code: "gu", value: 3 },
  { label: "हिंदी (Hindi)", code: "hi", value: 4 },
  { label: "ಕನ್ನಡ (Kannada)", code: "kn", value: 5 },
  { label: "മലയാളം (Malayalam)", code: "ml", value: 6 },
  { label: "मराठी (Marathi)", code: "mr", value: 7 },
  { label: "ଓରିଆ (Oriya)", code: "or", value: 8 },
  { label: "ਪੰਜਾਬੀ (Panjabi)", code: "pa", value: 9 },
  { label: "संस्कृतं (Sanskrit)", code: "sa", value: 10 },
  { label: "தமிழ் (Tamil)", code: "ta", value: 11 },
  { label: "తెలుగు (Telugu)", code: "te", value: 12 },
  { label: "اردو (Urdu)", code: "ur", value: 13 },
];

export const langSTS = [
    { label: "বাংলা (Bangla)", code: "bn", value: 1 },
    { label: "English", code: "en", value: 2 },
    { label: "ગુજરાતી (Gujarati)", code: "gu", value: 3 },
    { label: "हिंदी (Hindi)", code: "hi", value: 4 },
    { label: "ಕನ್ನಡ (Kannada)", code: "kn", value: 5 },
    { label: "मराठी (Marathi)", code: "mr", value: 6 },
    { label: "മലയാളം (Malayalam)", code: "ml", value: 7 },
    { label: "ଓରିଆ (Oriya)", code: "or", value: 8 },
    { label: "ਪੰਜਾਬੀ (Panjabi)", code: "pa", value: 9 },
    { label: "தமிழ் (Tamil)", code: "ta", value: 10 },
    { label: "తెలుగు (Telugu)", code: "te", value: 11 },
]

export const langTTS = [
  { label: "অসমীয়া (Assamese)", code: "as", value: 1 },
  { label: "বাংলা (Bangla)", code: "bn", value: 2 },
  { label: "बर (Boro)", code: "brx", value: 3 },
  { label: "English", code: "en", value: 4 },
  { label: "ગુજરાતી (Gujarati)", code: "gu", value: 5 },
  { label: "हिंदी (Hindi)", code: "hi", value: 6 },
  { label: "ಕನ್ನಡ (Kannada)", code: "kn", value: 7 },
  { label: "മലയാളം (Malayalam)", code: "ml", value: 8 },
  { label: "ꯃꯅꯤꯄꯨꯔꯤ (Manipuri (Meitei))", code: "mni", value: 9 },
  { label: "মনিপুরী (Manipuri (Bengali))", code: "mni_Beng", value: 10 },
  { label: "मराठी (Marathi)", code: "mr", value: 11 },
  { label: "ଓରିଆ (Oriya)", code: "or", value: 12 },
  { label: "ਪੰਜਾਬੀ (Panjabi)", code: "pa", value: 13 },
  { label: "Rajasthani", code: "raj", value: 14 },
  { label: "தமிழ் (Tamil)", code: "ta", value: 15 },
  { label: "తెలుగు (Telugu)", code: "te", value: 16 },
];

export const sampleRate = [
  { label: "8000 Hz", code: "8000", value: 1 },
  { label: "16000 Hz", code: "16000", value: 2 },
  { label: "48000 Hz", code: "48000", value: 3 },
]

export const voiceType = [
  { label: "Male", code: "Male", value: 1 },
  { label: "Female", code: "16000", value: 2 },
]
export const categoriesData = [
  {
    title: "Live Station",
    image: require("../../assets/images/location_live.png"),
  },
  {
    title: "Live Train",
    image: require("../../assets/images/traintotrain.png"),
  },
  {
    title: "From To",
    image: require("../../assets/images/location.png"),
  },
  {
    title: "Station Info",
    image: require("../../assets/images/information.png"),
  },
];

export let destinationData = [
  {
    train: "South Bihar Express",
    from: "Durg Jn.",
    to: "Rajendra Nagar Terminal",
    arr: "08:50",
    dep: "09:00",
    stop: "10",
    nos: "13287",
    platform: "5",
    late_hour: "",
    late_min: "45",
  },
  {
    train: "Howrah - Ahmedabad superfast Express",
    from: "Howrah",
    to: "Ahmedabad",
    arr: "10:55",
    dep: "11:00",
    stop: "5",
    nos: "12834",
    platform: "1",
    late_hour: "",
    late_min: "45",
  },
];

export const statesdata = [
  { label: "Andhra Pradesh", value: "1" },
  { label: "Arunachal Pradesh	", value: "2" },
  { label: "Assam", value: "3" },
  { label: "Bihar", value: "4" },
  { label: "Chhattisgarh", value: "5" },
  { label: "Goa", value: "6" },
  { label: "Gujarat", value: "7" },
  { label: "Haryana", value: "8" },
  { label: "Himachal Pradesh", value: "9" },
  { label: "Jharkhand", value: "10" },
  { label: "Karnataka", value: "11" },
  { label: "Kerala", value: "12" },
  { label: "Madhya Pradesh", value: "13" },
  { label: "Maharashtra", value: "14" },
  { label: "Manipur", value: "15" },
  { label: "Meghalaya", value: "16" },
  { label: "Mizoram", value: "17" },
  { label: "Nagaland", value: "18" },
  { label: "Odisha", value: "19" },
  { label: "Punjab", value: "20" },
  { label: "Rajasthan", value: "21" },
  { label: "Sikkim", value: "22" },
  { label: "Tamil Nadu", value: "23" },
  { label: "Telangana", value: "24" },
  { label: "Tripura", value: "25" },
  { label: "Uttar Pradesh	", value: "26" },
  { label: "Uttarakhand	", value: "27" },
  { label: "West Bengal", value: "28" },
];

export const langSelection = [
  { label: "অসমীয়া (Assamese)", code: "as", value: 1 },
  { label: "বাংলা (Bangla)", code: "bn", value: 2 },
  { label: "बर (Boro)", code: "brx", value: 3 },
  { label: "डोगरी (Dogri)", code: "doi", value: 4 },
  { label: "English", code: "en", value: 5 },
  { label: "गोंय (Goan-Konkani)", code: "gom", value: 6 },
  { label: "ગુજરાતી (Gujarati)", code: "gu", value: 7 },
  { label: "हिंदी (Hindi)", code: "hi", value: 8 },
  { label: "ಕನ್ನಡ (Kannada)", code: "kn", value: 9 },
  { label: "کاشمیری (Kashmiri (Arabic))", code: "ks", value: 10 },
  { label: "कश्मीरी (Kashmiri (Devanagari))", code: "ks_Deva", value: 11 },
  { label: "मैथिली (Maithili)", code: "mai", value: 12 },
  { label: "മലയാളം (Malayalam)", code: "ml", value: 13 },
  { label: "ꯃꯅꯤꯄꯨꯔꯤ (Manipuri (Meitei))", code: "mni", value: 14 },
  { label: "মনিপুরী (Manipuri (Bengali))", code: "mni_Beng", value: 15 },
  { label: "मराठी (Marathi)", code: "mr", value: 16 },
  { label: "नेपाली (Nepali)", code: "ne", value: 17 },
  { label: "ଓରିଆ (Oriya)", code: "or", value: 18 },
  { label: "ਪੰਜਾਬੀ (Panjabi)", code: "pa", value: 19 },
  { label: "संस्कृतं (Sanskrit)", code: "sa", value: 20 },
  { label: "ᱥᱚᱱᱛᱟᱞᱤ ᱾ (Santali)", code: "sat", value: 21 },
  { label: "سنڌی (Sindhi (Arabic))", code: "sd", value: 22 },
  { label: "सिंधी (Sindhi (Devanagari))", code: "sd_Deva", value: 23 },
  { label: "தமிழ் (Tamil)", code: "ta", value: 24 },
  { label: "తెలుగు (Telugu)", code: "te", value: 25 },
  { label: "اردو (Urdu)", code: "ur", value: 26 },
];